/* =========================================================
   RETROBOX V2.1 - BANCO DE JOGOS
   Jogos cadastrados a partir da lista fornecida pelo usuário.
   Para adicionar um jogo: { id, name, console, url }
========================================================= */

const CONSOLES = {
  nes:       { id:"nes", name:"Nintendo", icon:"🎮", className:"nes" },
  snes:      { id:"snes", name:"Super Nintendo", icon:"🕹️", className:"snes" },
  n64:       { id:"n64", name:"Nintendo 64", icon:"🟣", className:"n64" },
  gb:        { id:"gb", name:"Game Boy", icon:"🟦", className:"gb" },
  gbc:       { id:"gbc", name:"Game Boy Color", icon:"🟨", className:"gbc" },
  gba:       { id:"gba", name:"Game Boy Advance", icon:"🟩", className:"gba" },
  megadrive: { id:"megadrive", name:"Mega Drive", icon:"🔵", className:"megadrive" },
  atari:     { id:"atari", name:"Atari", icon:"🕹️", className:"atari" }
};

const JOGOS = [
  {id:"chrono-trigger",name:"Chrono Trigger",console:"snes",url:"https://emulatorgameszone.com/embed/game/chrono-trigger"},
  {id:"magical-quest-3-starring-mickey-and-donald",name:"Magical Quest 3: Starring Mickey and Donald",console:"snes",url:"https://emulatorgameszone.com/embed/game/magical-quest-3-starring-mickey-and-donald"},
  {id:"top-gear",name:"Top Gear",console:"snes",url:"https://emulatorgameszone.com/embed/game/top-gear"},
  {id:"super-metroid",name:"Super Metroid",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-metroid"},
  {id:"dragon-ball-z-super-butouden-3",name:"Dragon Ball Z Super Butouden 3",console:"snes",url:"https://emulatorgameszone.com/embed/game/dragon-ball-z-super-butouden-3"},
  {id:"final-fight-3",name:"Final Fight 3",console:"snes",url:"https://emulatorgameszone.com/embed/game/final-fight-3"},
  {id:"final-fantasy-iv",name:"Final Fantasy IV",console:"snes",url:"https://emulatorgameszone.com/embed/game/final-fantasy-iv"},
  {id:"final-fantasy-v",name:"Final Fantasy V",console:"snes",url:"https://emulatorgameszone.com/embed/game/final-fantasy-v"},
  {id:"breath-of-fire-ii",name:"Breath Of Fire II",console:"snes",url:"https://emulatorgameszone.com/embed/game/breath-of-fire-ii"},
  {id:"spider-man-and-the-x-men-in-arcade-s-revenge",name:"Spider Man And The X Men In Arcade's Revenge",console:"snes",url:"https://emulatorgameszone.com/embed/game/spider-man-and-the-x-men-in-arcade-s-revenge"},
  {id:"batman-forever",name:"Batman Forever",console:"snes",url:"https://emulatorgameszone.com/embed/game/batman-forever"},
  {id:"super-star-wars-return-of-the-jedi",name:"Super Star Wars Return Of The Jedi",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-star-wars-return-of-the-jedi"},
  {id:"harvest-moon",name:"Harvest Moon",console:"snes",url:"https://emulatorgameszone.com/embed/game/harvest-moon"},
  {id:"super-mario-world-2-yoshi-s-island",name:"Super Mario World 2 Yoshi's Island",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-mario-world-2-yoshi-s-island"},
  {id:"castlevania-dracula-x",name:"Castlevania Dracula X",console:"snes",url:"https://emulatorgameszone.com/embed/game/castlevania-dracula-x"},
  {id:"super-mario-kart",name:"Super Mario Kart",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-mario-kart"},
  {id:"super-mario-all-stars",name:"Super Mario All Stars",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-mario-all-stars"},
  {id:"super-mario-world",name:"Super Mario World",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-mario-world"},
  {id:"mega-man-x",name:"Mega Man X",console:"snes",url:"https://emulatorgameszone.com/embed/game/mega-man-x"},
  {id:"super-street-fighter-ii",name:"Super Street Fighter II",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-street-fighter-ii"},
  {id:"ultimate-mortal-kombat-3",name:"Ultimate Mortal Kombat 3",console:"snes",url:"https://emulatorgameszone.com/embed/game/ultimate-mortal-kombat-3"},
  {id:"donkey-kong-country-3-dixie-kong-s-double-trouble",name:"Donkey Kong Country 3 Dixie Kong's Double Trouble",console:"snes",url:"https://emulatorgameszone.com/embed/game/donkey-kong-country-3-dixie-kong-s-double-trouble"},
  {id:"super-bomberman-3",name:"Super Bomberman 3",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-bomberman-3"},
  {id:"super-bomberman-4",name:"Super Bomberman 4",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-bomberman-4"},
  {id:"donkey-kong-country-2-diddy-s-kong-quest",name:"Donkey Kong Country 2 Diddy's Kong Quest",console:"snes",url:"https://emulatorgameszone.com/embed/game/donkey-kong-country-2-diddy-s-kong-quest"},
  {id:"donkey-kong-country",name:"Donkey Kong Country",console:"snes",url:"https://emulatorgameszone.com/embed/game/donkey-kong-country"},
  {id:"the-legend-of-zelda-a-link-to-the-past",name:"The Legend Of Zelda A Link To The Past",console:"snes",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda-a-link-to-the-past"},
  {id:"super-bomberman",name:"Super Bomberman",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-bomberman"},
  {id:"super-bomberman-2",name:"Super Bomberman 2",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-bomberman-2"},
  {id:"x-men-mutant-apocalypse",name:"X Men Mutant Apocalypse",console:"snes",url:"https://emulatorgameszone.com/embed/game/x-men-mutant-apocalypse"},
  {id:"top-gear-3000",name:"Top Gear 3000",console:"snes",url:"https://emulatorgameszone.com/embed/game/top-gear-3000"},
  {id:"top-gear-2",name:"Top Gear 2",console:"snes",url:"https://emulatorgameszone.com/embed/game/top-gear-2"},
  {id:"dragon-ball-z-super-butouden",name:"Dragon Ball Z Super Butouden",console:"snes",url:"https://emulatorgameszone.com/embed/game/dragon-ball-z-super-butouden"},
  {id:"super-mario-rpg-legend-of-the-seven-stars",name:"Super Mario RPG Legend Of The Seven Stars",console:"snes",url:"https://emulatorgameszone.com/embed/game/super-mario-rpg-legend-of-the-seven-stars"},
  {id:"mega-man-7",name:"Mega Man 7",console:"snes",url:"https://emulatorgameszone.com/embed/game/mega-man-7"},
  {id:"mega-man-x3",name:"Mega Man X3",console:"snes",url:"https://emulatorgameszone.com/embed/game/mega-man-x3"},
  {id:"mega-man-x2",name:"Mega Man X2",console:"snes",url:"https://emulatorgameszone.com/embed/game/mega-man-x2"},
  {id:"mortal-kombat-ii",name:"Mortal Kombat II",console:"snes",url:"https://emulatorgameszone.com/embed/game/mortal-kombat-ii"},
  {id:"double-dragon-v-the-shadow-falls",name:"Double Dragon V The Shadow Falls",console:"snes",url:"https://emulatorgameszone.com/embed/game/double-dragon-v-the-shadow-falls"},
  {id:"metroid",name:"Metroid",console:"nes",url:"https://emulatorgameszone.com/embed/game/metroid"},
  {id:"wwf-wrestlemania-challenge",name:"WWF Wrestlemania Challenge",console:"nes",url:"https://emulatorgameszone.com/embed/game/wwf-wrestlemania-challenge"},
  {id:"star-wars",name:"Star Wars",console:"nes",url:"https://emulatorgameszone.com/embed/game/star-wars"},
  {id:"tetris",name:"Tetris",console:"nes",url:"https://emulatorgameszone.com/embed/game/tetris"},
  {id:"kirby-s-adventure",name:"Kirby's Adventure",console:"nes",url:"https://emulatorgameszone.com/embed/game/kirby-s-adventure"},
  {id:"the-uncanny-x-men",name:"The Uncanny X Men",console:"nes",url:"https://emulatorgameszone.com/embed/game/the-uncanny-x-men"},
  {id:"castlevania",name:"Castlevania",console:"nes",url:"https://emulatorgameszone.com/embed/game/castlevania"},
  {id:"adventure-island-iii",name:"Adventure Island III",console:"nes",url:"https://emulatorgameszone.com/embed/game/adventure-island-iii"},
  {id:"adventure-island-iv",name:"Adventure Island IV",console:"nes",url:"https://emulatorgameszone.com/embed/game/adventure-island-iv"},
  {id:"adventure-island-ii",name:"Adventure Island II",console:"nes",url:"https://emulatorgameszone.com/embed/game/adventure-island-ii"},
  {id:"adventure-island-i",name:"Adventure Island I",console:"nes",url:"https://emulatorgameszone.com/embed/game/adventure-island-i"},
  {id:"dr-mario",name:"Dr Mario",console:"nes",url:"https://emulatorgameszone.com/embed/game/dr-mario"},
  {id:"super-mario-bros-3",name:"Super Mario Bros 3",console:"nes",url:"https://emulatorgameszone.com/embed/game/super-mario-bros-3"},
  {id:"super-mario-bros-2",name:"Super Mario Bros 2",console:"nes",url:"https://emulatorgameszone.com/embed/game/super-mario-bros-2"},
  {id:"super-mario-bros",name:"Super Mario Bros",console:"nes",url:"https://emulatorgameszone.com/embed/game/super-mario-bros"},
  {id:"contra",name:"Contra",console:"nes",url:"https://emulatorgameszone.com/embed/game/contra"},
  {id:"teenage-mutant-ninja-turtles",name:"Teenage Mutant Ninja Turtles",console:"nes",url:"https://emulatorgameszone.com/embed/game/teenage-mutant-ninja-turtles"},
  {id:"mega-man-5",name:"Mega Man 5",console:"nes",url:"https://emulatorgameszone.com/embed/game/mega-man-5"},
  {id:"mega-man-4",name:"Mega Man 4",console:"nes",url:"https://emulatorgameszone.com/embed/game/mega-man-4"},
  {id:"mega-man-3",name:"Mega Man 3",console:"nes",url:"https://emulatorgameszone.com/embed/game/mega-man-3"},
  {id:"mega-man-2",name:"Mega Man 2",console:"nes",url:"https://emulatorgameszone.com/embed/game/mega-man-2"},
  {id:"mega-man-1",name:"Mega Man 1",console:"nes",url:"https://emulatorgameszone.com/embed/game/mega-man-1"},
  {id:"teenage-mutant-ninja-turtles-iii-the-manhattan-project",name:"Teenage Mutant Ninja Turtles III The Manhattan Project",console:"nes",url:"https://emulatorgameszone.com/embed/game/teenage-mutant-ninja-turtles-iii-the-manhattan-project"},
  {id:"bomberman",name:"Bomberman",console:"nes",url:"https://emulatorgameszone.com/embed/game/bomberman"},
  {id:"bomberman-ii",name:"Bomberman II",console:"nes",url:"https://emulatorgameszone.com/embed/game/bomberman-ii"},
  {id:"ninja-gaiden-iii-the-ancient-ship-of-doom",name:"Ninja Gaiden III The Ancient Ship Of Doom",console:"nes",url:"https://emulatorgameszone.com/embed/game/ninja-gaiden-iii-the-ancient-ship-of-doom"},
  {id:"zelda-ii-the-adventure-of-link",name:"Zelda II The Adventure Of Link",console:"nes",url:"https://emulatorgameszone.com/embed/game/zelda-ii-the-adventure-of-link"},
  {id:"the-legend-of-zelda",name:"The Legend Of Zelda",console:"nes",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda"},
  {id:"duke-nukem-zero-hour",name:"Duke Nukem Zero Hour",console:"n64",url:"https://emulatorgameszone.com/embed/game/duke-nukem-zero-hour"},
  {id:"duke-nukem-64",name:"Duke Nukem 64",console:"n64",url:"https://emulatorgameszone.com/embed/game/duke-nukem-64"},
  {id:"doom-64",name:"Doom 64",console:"n64",url:"https://emulatorgameszone.com/embed/game/doom-64"},
  {id:"goldeneye-007",name:"Goldeneye 007",console:"n64",url:"https://emulatorgameszone.com/embed/game/goldeneye-007"},
  {id:"mario-kart-64",name:"Mario Kart 64",console:"n64",url:"https://emulatorgameszone.com/embed/game/mario-kart-64"},
  {id:"international-superstar-soccer-64",name:"International Superstar Soccer 64",console:"n64",url:"https://emulatorgameszone.com/embed/game/international-superstar-soccer-64"},
  {id:"road-rash-64",name:"Road Rash 64",console:"n64",url:"https://emulatorgameszone.com/embed/game/road-rash-64"},
  {id:"wwf-no-mercy",name:"WWF No Mercy",console:"n64",url:"https://emulatorgameszone.com/embed/game/wwf-no-mercy"},
  {id:"star-wars-shadows-of-the-empire",name:"Star Wars Shadows Of The Empire",console:"n64",url:"https://emulatorgameszone.com/embed/game/star-wars-shadows-of-the-empire"},
  {id:"mario-party-3",name:"Mario Party 3",console:"n64",url:"https://emulatorgameszone.com/embed/game/mario-party-3"},
  {id:"mario-tennis",name:"Mario Tennis",console:"n64",url:"https://emulatorgameszone.com/embed/game/mario-tennis"},
  {id:"super-smash-bros",name:"Super Smash Bros",console:"n64",url:"https://emulatorgameszone.com/embed/game/super-smash-bros"},
  {id:"castlevania-legacy-of-darkness",name:"Castlevania Legacy Of Darkness",console:"n64",url:"https://emulatorgameszone.com/embed/game/castlevania-legacy-of-darkness"},
  {id:"harvest-moon-64",name:"Harvest Moon 64",console:"n64",url:"https://emulatorgameszone.com/embed/game/harvest-moon-64"},
  {id:"mortal-kombat-trilogy",name:"Mortal Kombat Trilogy",console:"n64",url:"https://emulatorgameszone.com/embed/game/mortal-kombat-trilogy"},
  {id:"bomberman-64",name:"Bomberman 64",console:"n64",url:"https://emulatorgameszone.com/embed/game/bomberman-64"},
  {id:"the-legend-of-zelda-majora-s-mask",name:"The Legend Of Zelda Majora's Mask",console:"n64",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda-majora-s-mask"},
  {id:"the-legend-of-zelda-ocarina-of-time",name:"The Legend Of Zelda Ocarina Of Time",console:"n64",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda-ocarina-of-time"},
  {id:"donkey-kong-64",name:"Donkey Kong 64",console:"n64",url:"https://emulatorgameszone.com/embed/game/donkey-kong-64"},
  {id:"super-mario-64",name:"Super Mario 64",console:"n64",url:"https://emulatorgameszone.com/embed/game/super-mario-64"},
  {id:"yoshi-s-story",name:"Yoshi's Story",console:"n64",url:"https://emulatorgameszone.com/embed/game/yoshi-s-story"},
  {id:"mortal-kombat-4",name:"Mortal Kombat 4",console:"n64",url:"https://emulatorgameszone.com/embed/game/mortal-kombat-4"},
  {id:"mortal-kombat-mythologies-sub-zero",name:"Mortal Kombat Mythologies Sub Zero",console:"n64",url:"https://emulatorgameszone.com/embed/game/mortal-kombat-mythologies-sub-zero"},
  {id:"top-gear-rally-2",name:"Top Gear Rally 2",console:"n64",url:"https://emulatorgameszone.com/embed/game/top-gear-rally-2"},
  {id:"yu-gi-oh-duel-monsters",name:"Yu Gi Oh Duel Monsters",console:"gb",url:"https://emulatorgameszone.com/embed/game/yu-gi-oh-duel-monsters"},
  {id:"top-gun-guts-and-glory",name:"Top Gun Guts And Glory",console:"gb",url:"https://emulatorgameszone.com/embed/game/top-gun-guts-and-glory"},
  {id:"taz-mania-2",name:"Taz Mania 2",console:"gb",url:"https://emulatorgameszone.com/embed/game/taz-mania-2"},
  {id:"the-legend-of-zelda-link-s-awakening",name:"The Legend Of Zelda Link's Awakening",console:"gb",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda-link-s-awakening"},
  {id:"super-mario-land-2-6-golden-coins",name:"Super Mario Land 2 6 Golden Coins",console:"gb",url:"https://emulatorgameszone.com/embed/game/super-mario-land-2-6-golden-coins"},
  {id:"donkey-kong-game-boy",name:"Donkey Kong Game Boy",console:"gb",url:"https://emulatorgameszone.com/embed/game/donkey-kong-game-boy"},
  {id:"pokemon-red-version",name:"Pokemon Red Version",console:"gb",url:"https://emulatorgameszone.com/embed/game/pokemon-red-version"},
  {id:"pokemon-blue-version",name:"Pokemon Blue Version",console:"gb",url:"https://emulatorgameszone.com/embed/game/pokemon-blue-version"},
  {id:"pokemon-yellow-version",name:"Pokemon Yellow Version",console:"gb",url:"https://emulatorgameszone.com/embed/game/pokemon-yellow-version"},
  {id:"pokemon-green-version",name:"Pokemon Green Version",console:"gb",url:"https://emulatorgameszone.com/embed/game/pokemon-green-version"},
  {id:"paperboy",name:"Paperboy",console:"gbc",url:"https://emulatorgameszone.com/embed/game/paperboy"},
  {id:"tom-and-jerry-in-mouse-attacks",name:"Tom And Jerry In Mouse Attacks",console:"gbc",url:"https://emulatorgameszone.com/embed/game/tom-and-jerry-in-mouse-attacks"},
  {id:"the-lion-king-simba-s-mighty-adventure-gbc",name:"The Lion King Simba's Mighty Adventure GBC",console:"gbc",url:"https://emulatorgameszone.com/embed/game/the-lion-king-simba-s-mighty-adventure-gbc"},
  {id:"dragon-ball-z-legendary-super-warriors",name:"Dragon Ball Z Legendary Super Warriors",console:"gbc",url:"https://emulatorgameszone.com/embed/game/dragon-ball-z-legendary-super-warriors"},
  {id:"batman-chaos-in-gotham",name:"Batman Chaos In Gotham",console:"gbc",url:"https://emulatorgameszone.com/embed/game/batman-chaos-in-gotham"},
  {id:"tomb-raider-curse-of-the-sword",name:"Tomb Raider Curse Of The Sword",console:"gbc",url:"https://emulatorgameszone.com/embed/game/tomb-raider-curse-of-the-sword"},
  {id:"spider-man-2-the-sinister-six",name:"Spider Man 2 The Sinister Six",console:"gbc",url:"https://emulatorgameszone.com/embed/game/spider-man-2-the-sinister-six"},
  {id:"resident-evil-gaiden",name:"Resident Evil Gaiden",console:"gbc",url:"https://emulatorgameszone.com/embed/game/resident-evil-gaiden"},
  {id:"x-men-wolverine-s-rage",name:"X Men Wolverine's Rage",console:"gbc",url:"https://emulatorgameszone.com/embed/game/x-men-wolverine-s-rage"},
  {id:"pokemon-crystal-version",name:"Pokemon Crystal Version",console:"gbc",url:"https://emulatorgameszone.com/embed/game/pokemon-crystal-version"},
  {id:"pokemon-silver-version",name:"Pokemon Silver Version",console:"gbc",url:"https://emulatorgameszone.com/embed/game/pokemon-silver-version"},
  {id:"pokemon-gold-version",name:"Pokemon Gold Version",console:"gbc",url:"https://emulatorgameszone.com/embed/game/pokemon-gold-version"},
  {id:"the-legend-of-zelda-oracle-of-seasons",name:"The Legend Of Zelda Oracle Of Seasons",console:"gbc",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda-oracle-of-seasons"},
  {id:"the-legend-of-zelda-oracle-of-ages",name:"The Legend Of Zelda Oracle Of Ages",console:"gbc",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda-oracle-of-ages"},
  {id:"the-legend-of-zelda-link-s-awakening-dx",name:"The Legend Of Zelda Link's Awakening Dx",console:"gbc",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda-link-s-awakening-dx"},
  {id:"top-gear-pocket",name:"Top Gear Pocket",console:"gbc",url:"https://emulatorgameszone.com/embed/game/top-gear-pocket"},
  {id:"kingdom-hearts-chain-of-memories",name:"Kingdom Hearts Chain Of Memories",console:"gba",url:"https://emulatorgameszone.com/embed/game/kingdom-hearts-chain-of-memories"},
  {id:"duke-nukem-advance",name:"Duke Nukem Advance",console:"gba",url:"https://emulatorgameszone.com/embed/game/duke-nukem-advance"},
  {id:"fifa-07",name:"Fifa 07",console:"gba",url:"https://emulatorgameszone.com/embed/game/fifa-07"},
  {id:"fifa-06",name:"Fifa 06",console:"gba",url:"https://emulatorgameszone.com/embed/game/fifa-06"},
  {id:"top-gear-gt-championship",name:"Top Gear GT Championship",console:"gba",url:"https://emulatorgameszone.com/embed/game/top-gear-gt-championship"},
  {id:"worms-blast",name:"Worms Blast",console:"gba",url:"https://emulatorgameszone.com/embed/game/worms-blast"},
  {id:"driver-2-advance",name:"Driver 2 Advance",console:"gba",url:"https://emulatorgameszone.com/embed/game/driver-2-advance"},
  {id:"doom-ii",name:"Doom II",console:"gba",url:"https://emulatorgameszone.com/embed/game/doom-ii"},
  {id:"lego-star-wars-ii-the-original-trilogy",name:"Lego Star Wars II The Original Trilogy",console:"gba",url:"https://emulatorgameszone.com/embed/game/lego-star-wars-ii-the-original-trilogy"},
  {id:"yu-gi-oh-worldwide-edition-stairway-to-the-destined-duel",name:"Yu Gi Oh Worldwide Edition Stairway To The Destined Duel",console:"gba",url:"https://emulatorgameszone.com/embed/game/yu-gi-oh-worldwide-edition-stairway-to-the-destined-duel"},
  {id:"yu-gi-oh-gx-duel-academy",name:"Yu Gi Oh Gx Duel Academy",console:"gba",url:"https://emulatorgameszone.com/embed/game/yu-gi-oh-gx-duel-academy"},
  {id:"yu-gi-oh-ultimate-masters-world-championship-tournament-2006",name:"Yu Gi Oh Ultimate Masters World Championship Tournament 2006",console:"gba",url:"https://emulatorgameszone.com/embed/game/yu-gi-oh-ultimate-masters-world-championship-tournament-2006"},
  {id:"yu-gi-oh-7-trials-to-glory-world-championship-tournament-2005",name:"Yu Gi Oh 7 Trials To Glory World Championship Tournament 2005",console:"gba",url:"https://emulatorgameszone.com/embed/game/yu-gi-oh-7-trials-to-glory-world-championship-tournament-2005"},
  {id:"shonen-jump-s-one-piece",name:"Shonen Jump's One Piece",console:"gba",url:"https://emulatorgameszone.com/embed/game/shonen-jump-s-one-piece"},
  {id:"final-fantasy-tactics-advance",name:"Final Fantasy Tactics Advance",console:"gba",url:"https://emulatorgameszone.com/embed/game/final-fantasy-tactics-advance"},
  {id:"digimon-battle-spirit-2",name:"Digimon Battle Spirit 2",console:"gba",url:"https://emulatorgameszone.com/embed/game/digimon-battle-spirit-2"},
  {id:"metroid-zero-mission",name:"Metroid Zero Mission",console:"gba",url:"https://emulatorgameszone.com/embed/game/metroid-zero-mission"},
  {id:"metroid-fusion",name:"Metroid Fusion",console:"gba",url:"https://emulatorgameszone.com/embed/game/metroid-fusion"},
  {id:"prince-of-persia-the-sands-of-time",name:"Prince Of Persia The Sands Of Time",console:"gba",url:"https://emulatorgameszone.com/embed/game/prince-of-persia-the-sands-of-time"},
  {id:"tomb-raider-the-prophecy",name:"Tomb Raider The Prophecy",console:"gba",url:"https://emulatorgameszone.com/embed/game/tomb-raider-the-prophecy"},
  {id:"spider-man-2",name:"Spider Man 2",console:"gba",url:"https://emulatorgameszone.com/embed/game/spider-man-2"},
  {id:"spider-man-the-movie",name:"Spider Man The Movie",console:"gba",url:"https://emulatorgameszone.com/embed/game/spider-man-the-movie"},
  {id:"looney-tunes-back-in-action",name:"Looney Tunes Back In Action",console:"gba",url:"https://emulatorgameszone.com/embed/game/looney-tunes-back-in-action"},
  {id:"wario-land-4",name:"Wario Land 4",console:"gba",url:"https://emulatorgameszone.com/embed/game/wario-land-4"},
  {id:"pokemon-unbound",name:"Pokemon Unbound",console:"gba",url:"https://emulatorgameszone.com/embed/game/pokemon-unbound"},
  {id:"mario-party-advance",name:"Mario Party Advance",console:"gba",url:"https://emulatorgameszone.com/embed/game/mario-party-advance"},
  {id:"mario-kart-super-circuit",name:"Mario Kart Super Circuit",console:"gba",url:"https://emulatorgameszone.com/embed/game/mario-kart-super-circuit"},
  {id:"grand-theft-auto-advance",name:"Grand Theft Auto Advance",console:"gba",url:"https://emulatorgameszone.com/embed/game/grand-theft-auto-advance"},
  {id:"dragon-ball-z-supersonic-warriors",name:"Dragon Ball Z Supersonic Warriors",console:"gba",url:"https://emulatorgameszone.com/embed/game/dragon-ball-z-supersonic-warriors"},
  {id:"digimon-battle-spirit",name:"Digimon Battle Spirit",console:"gba",url:"https://emulatorgameszone.com/embed/game/digimon-battle-spirit"},
  {id:"breath-of-fire",name:"Breath Of Fire",console:"gba",url:"https://emulatorgameszone.com/embed/game/breath-of-fire"},
  {id:"naruto-ninja-council-2",name:"Naruto Ninja Council 2",console:"gba",url:"https://emulatorgameszone.com/embed/game/naruto-ninja-council-2"},
  {id:"naruto-ninja-council",name:"Naruto Ninja Council",console:"gba",url:"https://emulatorgameszone.com/embed/game/naruto-ninja-council"},
  {id:"need-for-speed-most-wanted",name:"Need For Speed Most Wanted",console:"gba",url:"https://emulatorgameszone.com/embed/game/need-for-speed-most-wanted"},
  {id:"need-for-speed-underground-2",name:"Need For Speed Underground 2",console:"gba",url:"https://emulatorgameszone.com/embed/game/need-for-speed-underground-2"},
  {id:"need-for-speed-underground",name:"Need For Speed Underground",console:"gba",url:"https://emulatorgameszone.com/embed/game/need-for-speed-underground"},
  {id:"tekken-advance",name:"Tekken Advance",console:"gba",url:"https://emulatorgameszone.com/embed/game/tekken-advance"},
  {id:"tomb-raider-legend",name:"Tomb Raider Legend",console:"gba",url:"https://emulatorgameszone.com/embed/game/tomb-raider-legend"},
  {id:"super-mario-advance-3-yoshi-s-island",name:"Super Mario Advance 3 Yoshi's Island",console:"gba",url:"https://emulatorgameszone.com/embed/game/super-mario-advance-3-yoshi-s-island"},
  {id:"castlevania-aria-of-sorrow",name:"Castlevania Aria Of Sorrow",console:"gba",url:"https://emulatorgameszone.com/embed/game/castlevania-aria-of-sorrow"},
  {id:"castlevania-circle-of-the-moon",name:"Castlevania Circle Of The Moon",console:"gba",url:"https://emulatorgameszone.com/embed/game/castlevania-circle-of-the-moon"},
  {id:"castlevania-harmony-of-dissonance",name:"Castlevania Harmony Of Dissonance",console:"gba",url:"https://emulatorgameszone.com/embed/game/castlevania-harmony-of-dissonance"},
  {id:"mega-man-and-bass",name:"Mega Man And Bass",console:"gba",url:"https://emulatorgameszone.com/embed/game/mega-man-and-bass"},
  {id:"mega-man-zero-3",name:"Mega Man Zero 3",console:"gba",url:"https://emulatorgameszone.com/embed/game/mega-man-zero-3"},
  {id:"mega-man-zero-2",name:"Mega Man Zero 2",console:"gba",url:"https://emulatorgameszone.com/embed/game/mega-man-zero-2"},
  {id:"mega-man-zero",name:"Mega Man Zero",console:"gba",url:"https://emulatorgameszone.com/embed/game/mega-man-zero"},
  {id:"street-fighter-alpha-3",name:"Street Fighter Alpha 3",console:"gba",url:"https://emulatorgameszone.com/embed/game/street-fighter-alpha-3"},
  {id:"mortal-kombat-tournament-edition",name:"Mortal Kombat Tournament Edition",console:"gba",url:"https://emulatorgameszone.com/embed/game/mortal-kombat-tournament-edition"},
  {id:"mortal-kombat-deadly-alliance",name:"Mortal Kombat Deadly Alliance",console:"gba",url:"https://emulatorgameszone.com/embed/game/mortal-kombat-deadly-alliance"},
  {id:"the-legend-of-zelda-the-minish-cap",name:"The Legend Of Zelda The Minish Cap",console:"gba",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda-the-minish-cap"},
  {id:"the-legend-of-zelda-four-swords",name:"The Legend Of Zelda Four Swords",console:"gba",url:"https://emulatorgameszone.com/embed/game/the-legend-of-zelda-four-swords"},
  {id:"crash-bandicoot-purple-riptos-rampage",name:"Crash Bandicoot Purple Riptos Rampage",console:"gba",url:"https://emulatorgameszone.com/embed/game/crash-bandicoot-purple-riptos-rampage"},
  {id:"sonic-advance-3",name:"Sonic Advance 3",console:"gba",url:"https://emulatorgameszone.com/embed/game/sonic-advance-3"},
  {id:"sonic-advance-2",name:"Sonic Advance 2",console:"gba",url:"https://emulatorgameszone.com/embed/game/sonic-advance-2"},
  {id:"sonic-advance",name:"Sonic Advance",console:"gba",url:"https://emulatorgameszone.com/embed/game/sonic-advance"},
  {id:"crash-nitro-kart",name:"Crash Nitro Kart",console:"gba",url:"https://emulatorgameszone.com/embed/game/crash-nitro-kart"},
  {id:"pokemon-emerald-version",name:"Pokemon Emerald Version",console:"gba",url:"https://emulatorgameszone.com/embed/game/pokemon-emerald-version"},
  {id:"pokemon-leafgreen-version",name:"Pokemon Leafgreen Version",console:"gba",url:"https://emulatorgameszone.com/embed/game/pokemon-leafgreen-version"},
  {id:"pokemon-firered-version",name:"Pokemon Firered Version",console:"gba",url:"https://emulatorgameszone.com/embed/game/pokemon-firered-version"},
  {id:"pokemon-ruby-version",name:"Pokemon Ruby Version",console:"gba",url:"https://emulatorgameszone.com/embed/game/pokemon-ruby-version"},
  {id:"pokemon-sapphire-version",name:"Pokemon Sapphire Version",console:"gba",url:"https://emulatorgameszone.com/embed/game/pokemon-sapphire-version"},
  {id:"kirby-nightmare-in-dream-land",name:"Kirby Nightmare In Dream Land",console:"gba",url:"https://emulatorgameszone.com/embed/game/kirby-nightmare-in-dream-land"},
  {id:"metal-slug-advance",name:"Metal Slug Advance",console:"gba",url:"https://emulatorgameszone.com/embed/game/metal-slug-advance"},
  {id:"road-rash-3",name:"Road Rash 3",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/road-rash-3"},
  {id:"road-rash-ii",name:"Road Rash II",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/road-rash-ii"},
  {id:"streets-of-rage-3",name:"Streets of Rage 3",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/streets-of-rage-3"},
  {id:"streets-of-rage-2",name:"Streets of Rage 2",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/streets-of-rage-2"},
  {id:"mortal-kombat",name:"Mortal Kombat",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/mortal-kombat"},
  {id:"fatal-fury-2",name:"Fatal Fury 2",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/fatal-fury-2"},
  {id:"sonic-the-hedgehog",name:"Sonic the Hedgehog",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/sonic-the-hedgehog"},
  {id:"sonic-the-hedgehog-2",name:"Sonic the Hedgehog 2",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/sonic-the-hedgehog-2"},
  {id:"sonic-the-hedgehog-3",name:"Sonic the Hedgehog 3",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/sonic-the-hedgehog-3"},
  {id:"sonic-and-knuckles",name:"Sonic and Knuckles",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/sonic-and-knuckles"},
  {id:"sonic-3d-blast",name:"Sonic 3D Blast",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/sonic-3d-blast"},
  {id:"streets-of-rage",name:"Streets of Rage",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/streets-of-rage"},
  {id:"sonic-3-and-knuckles",name:"Sonic 3 and Knuckles",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/sonic-3-and-knuckles"},
  {id:"street-fighter-ii-special-champion-edition",name:"Street Fighter II Special Champion Edition",console:"megadrive",url:"https://emulatorgameszone.com/embed/game/street-fighter-ii-special-champion-edition"},
];

function getAllGames() {
  return JOGOS.map(game => ({
    ...game,
    consoleInfo: CONSOLES[game.console] || {
      name:"Desconhecido", icon:"🎮", className:"unknown"
    }
  }));
}
